### ISSUE TITLE
What is $item?

### ISSUE THREAD

**Issue by willGreg** [kartik-v/yii2-widget-sidenav#4]
What is $item in below code? It continue throw me error undefined Variable $item, still I have metioned my link init.

` 'active' => ($item == 'useradmin/index')]`

**Comment by kartik-v** [comment]
Obviously - you need to define such variables in your programming code... it is part of your application design and development.

If you are referring to this variable on the demo page, this variable is passed to the view object as a parameter that helps identify the active status of the menu navigation item.

**Comment by willGreg** [comment]
Yes I understand but my question is it throw me $item is undefined. Still I have defined it's value as below:
`$item == 'useradmin/index'`

**Comment by willGreg** [comment]
```
['label' => 'Administration', 'icon' => 'user', 'active' => ($item == '/useradmin/index'),
  'items' => [
       ['label' => 'ABC Management', 'url' => Url::to(['/abc/index', type'=>SideNav::TYPE_PRIMARY]),'active' => ($item == 'index')],
       ['label' => 'pqr', 'url' => Url::to(['/pqr/index', 'type'=>SideNav::TYPE_PRIMARY]),'active' => ($item == 'pqr') ],
       ['label' => 'Wallet', 'url' => Url::to(['/wallet/index', 'type'=>SideNav::TYPE_PRIMARY]),'active' => ($item == 'wallet') ],
      ],
   ],
```
above is my code

**Comment by kartik-v** [comment]
> Yes I understand but my question is it throw me $item is undefined. Still I have defined it's value as below: `$item == 'useradmin/index'`

If you are planning to set a value for the variable `$item` then you need to set it like below
`$item = 'useradmin/index';`

The double equal to operator `==` does a equality check.

**Comment by willGreg** [comment]
okk thanks

It's work fine, but the active fields are remain active still I have selected another link in submenu. I have edited my code as you have mentioned in your demo for submenu.

And also improve the code, which you have mention in your demo code: 
[(http://demos.krajee.com/sidenav-demo/fiction/default#demo)]
Correct this line:
From:
`['label' => 'Event 1', 'url' => Url::to(['/site/event-1', 'type'=>$type]), 'active' => ($item == 'event-1')],`

To:
`['label' => 'Event 1', 'url' => Url::to(['/site/event-1', 'type'=>$type]), 'active' => ($item = 'event-1')],`

**Comment by kartik-v** [comment]
No that is incorrect. 

- Please read PHP documentation for difference between `=`  and `==`.
- If you are keen to understand the [example demo](http://demos.krajee.com/sidenav-demo/profile/default), then `$item` in the example demo is a parameter you must pass to your view. This has been mentioned in the CODE COMMENTS in the example demo link above. You can typically pass that by assigning `$item` in your render view params. Please read yii2 documentation on how you pass variables to the view.
- The `active` property above is a boolean value and the `$item == 'some-value'` returns a boolean output. 
- The `$item` logic as mentioned in the demo is NOT NECESSARY TO BE INCLUDED in YOUR CODE. It is JUST AN EXAMPLE that was shared in the [specific demo](http://demos.krajee.com/sidenav-demo/profile/default). You can just set `'active' => true` or `'active' => false` based on whatever logic your view needs to have.

**Comment by willGreg** [comment]
> I have modified my code as per logic that you have told about put active as true or false, bcoz it has 
> boolean value.
> But still it remain active it accepts only either true or false i want to make it only when that particular link will be get clicked!!!!!! and another remain inactive.
