### ISSUE TITLE
Method POST

### ISSUE THREAD

**Issue by crissty** [kartik-v/yii2-widget-sidenav#7]
HELLO,
HOW IS IT MADE THAT A MENU LINK IS SENT BY POST METHOD, INSTEAD OF GET METHOD?

THANKS!!

**Comment by crissty** [comment]
I have the same problem. I want one of menu links to be by post method. Have you found the solution?

Thanks!!

**Comment by kartik-v** [comment]
Please do not duplicate post over your post appearing as a new poster.

You need to write your own javascript code for this on click of each menu item to trigger your POST request (via AJAX or something similar by using a hidden form submit). By default `<a href`  links in native HTML trigger a GET call. Yii includes a feature as part of its Javascript library (when you include YiiAsset) that converts your links to POST if you set the property `data-method = 'post'`.

**Comment by crissty** [comment]
Thanks, but I have solved it adding a link to the label field, and commenting on the url field:

`[
  'label' => Html::a('LOG OUT ,['/user/logout'],['data-method' => 'post']),
  /* 'url' => '', */
]`

**Comment by nimaan1970** [comment]
['label' => 'Logout' , 'url'=>['default/logout', ], 'template' => '<a href="{url}" data-method="post" class="nav-link text-secondary nva-links" tyle="text-decoration:none" >{label}</a>',],

**Comment by nimaan1970** [comment]
[
	'label' => 'Logout' , 
	'url'=>['default/logout', ], 
	'template' => '<a href="{url}" data-method="post" class="nav-link text-secondary nva-links" tyle="text-decoration:none" >{label}</a>',
],

**Comment by nimaan1970** [comment]
![image](https://github.com/kartik-v/yii2-widget-sidenav/assets/25685849/88fa3f5b-9289-40dc-90a6-f87c31a4e0ea)

**Comment by nimaan1970** [comment]
![image](https://github.com/kartik-v/yii2-widget-sidenav/assets/25685849/cc9d6c73-97f3-4045-bdcc-839d1ab2b4fa)

**Comment by nimaan1970** [comment]
![image](https://github.com/kartik-v/yii2-widget-sidenav/assets/25685849/523685d4-d542-4a69-b62a-fa65cad95473)

**Comment by nimaan1970** [comment]
![image](https://github.com/kartik-v/yii2-widget-sidenav/assets/25685849/2ae10abe-ad13-4f8e-b174-a4883abf0fa0)

used in SideNav menu
